Pulp: add cron job that deletes container registries
Juniper/contrail-infra pull request #126
Opened 2018-01-29 14:41 UTC by jluk-codi

2018-01-29 14:46 UTC, wurbanski commented on modules/opencontrail_ci/manifests/logserver.pp
> +    content => 'puppet:///modules/opencontrail_ci/zuul-jobs-stats/logrotate',
:+1:

2018-02-02 08:45 UTC, kklimonda requested changes

2018-02-02 08:45 UTC, kklimonda commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +        print('Not removing', cont)
Change all print into logging statements and log to /var/log/{something}.log

2018-02-02 08:45 UTC, kklimonda commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +        # TODO handle already removed containers
Is it going to fail when container has already been deleted?

2018-02-02 08:45 UTC, kklimonda commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +    #print(container['Names'])
Remove commented out code

2018-02-08 12:11 UTC, kklimonda approved these changes

2018-02-08 12:12 UTC, merged