Adapt artifact curator to 5.0 build style
Juniper/contrail-infra pull request #164
Opened 2018-05-09 11:30 UTC by jluk-codi

- distro suffixes in repo names
- nightly builds are done in per-buildset registries, clean them
- nightly repos retention

2018-05-09 11:51 UTC, wurbanski requested changes
Left some requests for discussion.

2018-05-09 11:51 UTC, wurbanski commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
>  review_re = re.compile(r"""^\d+-\d+$""")
Maybe we should define specific length of review numbers? `{5,6}` should be enough and give a little more information

2018-05-09 11:51 UTC, wurbanski commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +review_repo_regex = re.compile(r"""^\d+-\d+-(centos|redhat)$""")
Maybe we should define specific length of review numbers? {5,6} should be enough and give a little more information

2018-05-09 11:51 UTC, wurbanski commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +            "centos74-updates", "opencontrail-tpc", "repo1",
Maybe we should use some naming convention for pulp repositories IDs? It's possible to change an ID but keep the friendly name intact.

2018-05-09 11:51 UTC, wurbanski commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +    active_changesets = [set_['change'] + "-" + set_['patchset'] + "-centos" for set_ in active_buildsets if set_['change'] and set_['patchset']]
How about we use some regex instead of `-centos` suffix? This way we're safe if we add per-review repos for rhel, fedora or any other distro.

2018-05-09 11:51 UTC, wurbanski commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +    print(cleanup_list)
Change to a `logger.info()` call.

2018-05-09 11:51 UTC, wurbanski commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +                sys.exit(1)
Why do we terminate the run on deletion error? We could just pass over it, but log the information about failed removal.

2018-05-09 12:57 UTC, kravvcuCL approved these changes

2018-05-23 12:13 UTC, jluk-codi commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
>  review_re = re.compile(r"""^\d+-\d+$""")
I don't think so, the review can have any number. I can add a comment with an explanation of the fields.

2018-05-23 12:13 UTC, jluk-codi commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +review_repo_regex = re.compile(r"""^\d+-\d+-(centos|redhat)$""")
Same as above.

2018-05-23 12:14 UTC, jluk-codi commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +            "centos74-updates", "opencontrail-tpc", "repo1",
This should be first covered in an RFC ;)

2018-05-23 12:15 UTC, jluk-codi commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +    print(cleanup_list)
Removed entirely.

2018-05-23 13:07 UTC, jluk-codi commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +                sys.exit(1)
Lots of dangling images I see. But this exit won't solve this anyways, removing.

2018-05-23 13:09 UTC, jluk-codi commented on modules/opencontrail_ci/files/pulp/artifact_curator.py
> +    active_changesets = [set_['change'] + "-" + set_['patchset'] + "-centos" for set_ in active_buildsets if set_['change'] and set_['patchset']]
Refactored to not use the name-faking step.

2018-05-30 07:32 UTC, wurbanski approved these changes

2018-05-30 07:54 UTC, merged