Install and configure nexus3-oss service
Juniper/contrail-infra pull request #177
Opened 2018-09-04 07:56 UTC by wurbanski

Contains manifest for installation and configuration of nexus3-oss service

* Adds puppet-nginx module
* Configures nginx as reverse proxy
* Uses nexus3 rpm signed and built in OBS (https://build.opensuse.org/package/show/home:woid:nexus3/nexus3-oss)

2018-09-05 09:55 UTC, jluk-codi requested changes

2018-09-05 09:55 UTC, jluk-codi commented on modules/opencontrail_ci/manifests/nexus_repository.pp
> +  gnupg_key { 'obs:woid:nexus3':
Change this name to something generic (nexus3_yum_gpg_key?)

2018-09-05 09:55 UTC, jluk-codi commented on modules/opencontrail_ci/manifests/nexus_repository.pp
> +  yumrepo {'obs:woid:nexus3':
Change this name to something generic (nexus3_yum_repo?)

2018-09-10 10:09 UTC, jluk-codi approved these changes

2018-09-10 10:11 UTC, diabelko approved these changes

2018-09-10 10:15 UTC, diabelko approved these changes

2018-09-10 10:15 UTC, merged