Add autossh for zuul executor log streaming.
Juniper/contrail-infra pull request #181
Opened 2018-09-27 14:44 UTC by kravvcuCL

2018-09-27 15:08 UTC, diabelko requested changes

2018-09-27 15:08 UTC, Diabelko commented on modules/opencontrail_ci/manifests/zuul_executor_autossh.pp
> +    subscribe => File['/etc/systemd/system/autossh-zuul.service'],
Subscribe, require, notify, before

2018-09-27 15:08 UTC, Diabelko commented on modules/opencontrail_ci/templates/autossh-zuul.service.erb
> +ExecStart=/usr/bin/autossh -i <%= @ssh_key_path %> -M <%= @monitoring_port %> -o "UserKnownHostsFile /dev/null" -o "StrictHostKeyChecking no" -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -N
Does autossh come with the system? If not, we need to install it.

2018-09-28 08:53 UTC, kravvcuCL commented on modules/opencontrail_ci/manifests/zuul_executor_autossh.pp
> +    subscribe => File['/etc/systemd/system/autossh-zuul.service'],
Done.

2018-09-28 08:53 UTC, kravvcuCL commented on modules/opencontrail_ci/templates/autossh-zuul.service.erb
> +ExecStart=/usr/bin/autossh -i <%= @ssh_key_path %> -M <%= @monitoring_port %> -o "UserKnownHostsFile /dev/null" -o "StrictHostKeyChecking no" -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -N
Done.

2018-09-28 14:06 UTC, diabelko approved these changes

2018-09-28 14:17 UTC, wurbanski approved these changes

2018-10-01 05:54 UTC, merged